### ISSUE TITLE
TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by sporkmonger** [petrslavotinek/grafana-carpetplot#2]
```
TypeError: Cannot read property 'time' of undefined
    at addXAxis (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500400088777:145:34)
    at addAxes (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500400088777:99:7)
    at addCarpetplot (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500400088777:72:7)
    at render (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500400088777:570:7)
    at f.eval (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500400088777:53:7)
    at f.emit (http://<redacted>/public/app/boot.74ebeed4.js:62:13842)
    at a.emit (http://<redacted>/public/app/boot.74ebeed4.js:62:15727)
    at CarpetPlotCtrl.a.render (http://<redacted>/public/app/boot.74ebeed4.js:56:2030)
    at f.CarpetPlotCtrl._this.onDataReceived (http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/carpetplot-ctrl.js?bust=1500400088777:137:19)
    at f.emit (http://<redacted>/public/app/boot.74ebeed4.js:62:13409)
    at a.emit (http://<redacted>/public/app/boot.74ebeed4.js:62:15727)
    at CarpetPlotCtrl.b.handleQueryResult (http://<redacted>/public/app/boot.74ebeed4.js:56:15010)
    at i (http://<redacted>/public/app/boot.74ebeed4.js:52:15288)
    at http://<redacted>/public/app/boot.74ebeed4.js:52:15710
    at o.$eval (http://<redacted>/public/app/boot.74ebeed4.js:52:22865)
    at o.$digest (http://<redacted>/public/app/boot.74ebeed4.js:52:21338)
    at o.$apply (http://<redacted>/public/app/boot.74ebeed4.js:52:23148)
    at http://<redacted>/public/app/boot.74ebeed4.js:52:19198
    at f (http://<redacted>/public/app/boot.74ebeed4.js:51:1421)
    at http://<redacted>/public/app/boot.74ebeed4.js:51:2882
```

**Comment by petrslavotinek** [comment]
Hi, could you please send some more info? What type of datasource are you using?
The data returned by your datasource seems to be empty.

**Comment by sporkmonger** [comment]
This actually happens before entering a metric at all, so that would make
sense. However, entering a metric doesn't work either because the JS code
has already hit an error and apparently can't recover once it does have
data?

**Comment by sporkmonger** [comment]
Also getting:

```
data.data[0] is undefined

addXAxis@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500499765643:145:7
addAxes@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500499765643:99:7
addCarpetplot@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500499765643:72:7
render@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500499765643:570:7
link/<@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/canvas/rendering.js?bust=1500499765643:53:7
f.prototype.emit@http://<redacted>/public/app/boot.74ebeed4.js:62:13834
execute/e</a.prototype.emit@http://<redacted>/public/app/boot.74ebeed4.js:62:15714
execute/m</a.prototype.render@http://<redacted>/public/app/boot.74ebeed4.js:56:2018
CarpetPlotCtrl/_this.onDataReceived@http://<redacted>/public/plugins/petrslavotinek-carpetplot-panel/carpetplot-ctrl.js?bust=1500499765643:137:13
f.prototype.emit@http://<redacted>/public/app/boot.74ebeed4.js:62:13404
execute/e</a.prototype.emit@http://<redacted>/public/app/boot.74ebeed4.js:62:15714
execute/k</b.prototype.handleQueryResult@http://<redacted>/public/app/boot.74ebeed4.js:56:14998
i@http://<redacted>/public/app/boot.74ebeed4.js:52:15288
l/<@http://<redacted>/public/app/boot.74ebeed4.js:52:15710
$eval@http://<redacted>/public/app/boot.74ebeed4.js:52:22861
$digest@http://<redacted>/public/app/boot.74ebeed4.js:52:21330
$apply@http://<redacted>/public/app/boot.74ebeed4.js:52:23146
x/i<@http://<redacted>/public/app/boot.74ebeed4.js:52:19196
f@http://<redacted>/public/app/boot.74ebeed4.js:51:1419
pb/k.defer/c<@http://<redacted>/public/app/boot.74ebeed4.js:51:2882
```

**Comment by sporkmonger** [comment]
Oh, there's a bunch.

```
TypeError: this.scope.hasData is not a function
```

and

```
TypeError: $canvas is undefined
```

**Comment by sporkmonger** [comment]
It's supposed to be a Prometheus datasource, but yeah, it doesn't really get that far.

**Comment by petrslavotinek** [comment]
I've installed Prometheus but wasn't able to reproduce the error. I've added check for data.data[0].
Could you try this updated version directly from this repository?
Just download it and copy it to /var/lib/grafana/plugins.

**Comment by sporkmonger** [comment]
Still doesn't work, now I get errors like:

```
Uncaught TypeError: Cannot read property 'autoHighlight' of undefined
    at triggerClickHoverEvent (jquery.flot.pie.js?bust=1500578146211:658)
    at HTMLCanvasElement.onMouseMove (jquery.flot.pie.js?bust=1500578146211:642)
    at HTMLCanvasElement.dispatch (boot.74ebeed4.js:49)
    at HTMLCanvasElement.q.handle (boot.74ebeed4.js:49)
```

**Comment by petrslavotinek** [comment]
This error's source is in flot library for pie chart. (jquery.flot.pie.js)
There's no autoHighlight property in carpet plot.
Do you have pie chart on the same dashboard?

**Comment by petrslavotinek** [comment]
Hi, are you still having these problems? There was wrong required version of grafana - should be 4.3.X instead of 4.X.X.
